version: '3.5'

services:
  producer:
    build: './producer'
    image: tweet_producer
    container_name: tweet_producer
    networks:
      - application

# Give this composition access to the Kafka network
networks:
  application:
    driver: bridge